### ISSUE TITLE
Exception im Frontend - Anfrage bei bisher unbekannten Restaurant

### ISSUE THREAD

**Issue by wasnertobias** [okfde/froide-food#21]
Ich wollte gerade bei einem bisher nicht bekannten Restaurant eine Anfrage starten, leider wird dabei eine Exception im Frontend geworfen:

```
TypeError: Cannot read properties of undefined (reading 'laws')
    at a.defaultLaw (food-request.vue:192:44)
    at _n.get (vue.esm.js:4504:25)
    at _n.evaluate (vue.esm.js:4606:21)
    at a.defaultLaw (vue.esm.js:4860:17)
    at a.<anonymous> (food-request.vue?./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib/index.js??vue-loader-options:1:2609)
    at a.t._render (vue.esm.js:3578:22)
    at a.r (vue.esm.js:4090:21)
    at _n.get (vue.esm.js:4504:25)
    at _n.run (vue.esm.js:4579:22)
    at gn (vue.esm.js:4335:13)
```

Die Seite zeigt in dem Fall eine unendliche Ladeanimation an.

Ich kann gleich mal einen Blick reinwerfen in das Projekt, vielleicht kann ich ja selbst für einen Fix sorgen und einen Pull request stellen.

**Comment by wasnertobias** [comment]
Leider tu ich mir etwas schwer den Fehler zu reproduzieren, von einem quick fix bin ich auch entfernt.
